spring:
  application:
    name: devhub
  profiles:
    active: local

server:
  port: 8080

logging:
  level:
    com.secretminc.devhub: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE